# Generated by Django 5.0.6 on 2024-05-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0002_alter_pageview_referrer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_properties",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
