# Generated by Django 5.0.6 on 2024-05-28 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0003_alter_event_event_properties"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useragent",
            old_name="brower_version",
            new_name="browser_version",
        ),
    ]
