# Generated by Django 5.0.6 on 2024-05-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0004_rename_brower_version_useragent_browser_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageview",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
