# Generated by Django 5.0.6 on 2024-06-01 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0005_pageview_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ignore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ignore_regex",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "webiste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="track.website"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
