# Generated by Django 5.0.6 on 2024-06-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0006_ignore"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pageview",
            name="track_pagev_timesta_4f838d_idx",
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["timestamp", "website", "url"],
                name="track_pagev_timesta_332746_idx",
            ),
        ),
    ]
