# Generated by Django 5.0.6 on 2024-11-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0008_alter_utm_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(verbose_name='Tracking Base Url')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
