version: '3.11'
services:
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --no-input &&
             python manage.py migrate &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./src:/usr/src # Project source code
      - static_volume:/usr/src/static # Static files
      - media_volume:/usr/src/media # Media files
    expose:
      - 8000
    env_file:
      - ./src/core/.env
    depends_on:
      - redis

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/static
      - media_volume:/usr/src/media
    ports:
      - "80:80"
    depends_on:
      - web

  # caddy:
  #   build: ./caddy
  #   volumes:
  #     - static_volume:/usr/src/static
  #     - media_volume:/usr/src/media
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - web

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command:
      - redis-server

  celery_worker:
    build: .
    command: celery -A core worker -l INFO
    volumes:
      - ./src:/usr/src # Project source code
    env_file:
      - ./src/core/.env
    depends_on:
      - redis

  flower:
    build: .
    command: celery -A core flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - ./src:/usr/src # Project source code
    env_file:
      - ./src/core/.env
    depends_on:
      - redis
      - celery_worker

volumes:
  redis_data:
  static_volume:
  media_volume:
